# Generated by Django 4.0.1 on 2022-12-07 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('mat_no', models.CharField(max_length=15)),
                ('department', models.CharField(max_length=30)),
                ('level', models.IntegerField(choices=[(100, 100), (200, 200), (300, 300), (400, 400), (500, 500), (600, 600), (700, 700)])),
                ('school_fees', models.FileField(upload_to='student/school_fees')),
                ('hostel_application', models.FileField(upload_to='student/hostel_application')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='student/images')),
                ('booking', models.BooleanField(default=False)),
                ('space', models.CharField(blank=True, choices=[('UP', 'UP'), ('DOWN', 'DOWN')], default=None, max_length=5, null=True)),
                ('slug', models.SlugField()),
                ('stud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Portal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], default=None, max_length=6, null=True)),
                ('staff_num', models.CharField(max_length=15)),
                ('phone_number', models.IntegerField()),
                ('slug', models.SlugField(unique=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
