# Generated by Django 4.0.1 on 2022-12-07 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_name', models.CharField(max_length=10)),
                ('number_of_floors', models.IntegerField()),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('free_space', models.FloatField(default=100.0)),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_number', models.IntegerField()),
                ('number_of_rooms', models.IntegerField()),
                ('free_space', models.FloatField(default=100.0)),
                ('slug', models.SlugField()),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='halls.block')),
            ],
        ),
        migrations.CreateModel(
            name='SpaceUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Free', models.BooleanField(default=True)),
                ('Booked', models.BooleanField(default=False)),
                ('reserved', models.BooleanField(default=False)),
                ('room_type', models.CharField(blank=True, choices=[('roomA', 'roomA'), ('roomB', 'roomB')], max_length=6, null=True)),
                ('room_id', models.IntegerField(blank=True, null=True)),
                ('student', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.student')),
            ],
        ),
        migrations.CreateModel(
            name='SpaceDown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Free', models.BooleanField(default=True)),
                ('Booked', models.BooleanField(default=False)),
                ('reserved', models.BooleanField(default=False)),
                ('room_type', models.CharField(blank=True, choices=[('roomA', 'roomA'), ('roomB', 'roomB')], max_length=6, null=True)),
                ('room_id', models.IntegerField(blank=True, null=True)),
                ('student', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.student')),
            ],
        ),
        migrations.CreateModel(
            name='RoomC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField()),
                ('resource_in_use', models.BooleanField(default=False)),
                ('free_space', models.FloatField(default=100.0)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='halls.floor')),
                ('space_1', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='C_space1', to='halls.spaceup')),
                ('space_2', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='C_space2', to='halls.spacedown')),
                ('space_3', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='C_space3', to='halls.spaceup')),
                ('space_4', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='C_space4', to='halls.spacedown')),
            ],
        ),
        migrations.CreateModel(
            name='RoomB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField()),
                ('resource_in_use', models.BooleanField(default=False)),
                ('free_space', models.FloatField(default=100.0)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='halls.floor')),
                ('space_1', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='B_space1', to='halls.spaceup')),
                ('space_2', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='B_space2', to='halls.spacedown')),
                ('space_3', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='B_space3', to='halls.spaceup')),
                ('space_4', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='B_space4', to='halls.spacedown')),
                ('space_5', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='B_space5', to='halls.spaceup')),
                ('space_6', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='B_space6', to='halls.spacedown')),
            ],
        ),
        migrations.CreateModel(
            name='RoomA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField()),
                ('resource_in_use', models.BooleanField(default=False)),
                ('free_space', models.FloatField(default=100.0)),
                ('slug', models.SlugField()),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='halls.floor')),
                ('space_1', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Aspace1', to='halls.spaceup')),
                ('space_2', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Aspace2', to='halls.spacedown')),
                ('space_3', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Aspace3', to='halls.spaceup')),
                ('space_4', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Aspace4', to='halls.spacedown')),
                ('space_5', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Aspace5', to='halls.spaceup')),
                ('space_6', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Aspace6', to='halls.spacedown')),
                ('space_7', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Aspace7', to='halls.spaceup')),
                ('space_8', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Aspace8', to='halls.spacedown')),
            ],
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall_name', models.CharField(choices=[('Hall_1', 'Hall_1'), ('Hall_2', 'Hall_2'), ('Hall_3', 'Hall_3'), ('Hall_4', 'Hall_4'), ('Hall_5', 'Hall_5')], max_length=30, unique=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('number_of_rooms', models.IntegerField(null=True)),
                ('number_of_spaces', models.IntegerField(null=True)),
                ('back_img', models.ImageField(blank=True, null=True, upload_to='hall/images')),
                ('img_one', models.ImageField(blank=True, null=True, upload_to='hall/images')),
                ('img_two', models.ImageField(blank=True, null=True, upload_to='hall/images')),
                ('img_three', models.ImageField(blank=True, null=True, upload_to='hall/images')),
                ('descriptions', models.TextField(null=True)),
                ('free_space', models.FloatField(default=100.0)),
                ('admin_head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_head', to='users.portal')),
                ('portal_one', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_one', to='users.portal')),
                ('portal_two', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_two', to='users.portal')),
            ],
        ),
        migrations.AddField(
            model_name='block',
            name='hostel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='halls.hall'),
        ),
    ]
